In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hw8.ipynb")

# CPSC 330 - Applied Machine Learning

## Homework 8: Introduction to Computer vision and Time Series

**Due date: See [deliverable due dates](https://ubc-cs.github.io/cpsc330-2025W2/#deliverable-due-dates-tentative)**.

## Imports

In [2]:
from hashlib import sha1

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score

<!-- BEGIN QUESTION -->

<div class="alert alert-info">
    
## Instructions
rubric={points}

You will earn points for following these instructions and successfully submitting your work on Gradescope.  

### Group wotk instructions

**You may work with a partner on this homework and submit your assignment as a group.** Below are some instructions on working as a group.  
- The maximum group size is 2.
  
- Use group work as an opportunity to collaborate and learn new things from each other. 
- Be respectful to each other and make sure you understand all the concepts in the assignment well. 
- It's your responsibility to make sure that the assignment is submitted by one of the group members before the deadline. 
- You can find the instructions on how to do group submission on Gradescope [here](https://help.gradescope.com/article/m5qz2xsnjy-student-add-group-members).
- If you would like to use late tokens for the homework, all group members must have the necessary late tokens available. Please note that the late tokens will be counted for all members of the group.   


### General submission instructions

- Please **read carefully
[Use of Generative AI policy](https://ubc-cs.github.io/cpsc330-2025W2/syllabus#use-of-generative-ai-in-the-course)** before starting the homework assignment. 
- **Run all cells before submitting:** Go to `Kernel -> Restart Kernel and Clear All Outputs`, then select `Run -> Run All Cells`. This ensures your notebook runs cleanly from start to finish without errors.
  
- **Submit your files on Gradescope.**  
   - Upload only your `.ipynb` file **with outputs displayed** and any required output files.
     
   - Do **not** submit other files from your repository.  
   - If you need help, see the [Gradescope Student Guide](https://lthub.ubc.ca/guides/gradescope-student-guide/).  
- **Check that outputs render properly.**  
   - Make sure all plots and outputs appear in your submission.
     
   - If your `.ipynb` file is too large and doesn't render on Gradescope, also upload a PDF or HTML version so the TAs can view your work.  
- **Keep execution order clean.**  
   - Execution numbers must start at "1" and increase in order.
     
   - Notebooks without visible outputs may not be graded.  
   - Out-of-order or missing execution numbers may result in mark deductions.  
- **Follow course submission guidelines:** Review the [CPSC 330 homework instructions](https://ubc-cs.github.io/cpsc330-2025W2/docs/homework-instructions) for detailed guidance on completing and submitting assignments. 
   
</div>

_Points:_ 2

<!-- END QUESTION -->

<br><br>

## Exercise 1: time series prediction

In this exercise we'll be looking at a [dataset of avocado prices](https://www.kaggle.com/neuromusic/avocado-prices). You should start by downloading the dataset and storing it under the `data` folder. We will be forcasting average avocado price for the next week.

In [3]:
df = pd.read_csv("data/avocado.csv", parse_dates=["Date"], index_col=0)
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [4]:
df.shape

(18249, 13)

In [5]:
df["Date"].min()

Timestamp('2015-01-04 00:00:00')

In [6]:
df["Date"].max()

Timestamp('2018-03-25 00:00:00')

It looks like the data ranges from the start of 2015 to March 2018 (~2 years ago), for a total of 3.25 years or so. Let's split the data so that we have a 6 months of test data.

In [7]:
split_date = '20170925'
df_train = df[df["Date"] <= split_date]
df_test  = df[df["Date"] >  split_date]

In [8]:
assert len(df_train) + len(df_test) == len(df)

<br><br>

<!-- BEGIN QUESTION -->

### 1.1 How many time series? 
rubric={points:4}

In the [Rain in Australia](https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package) dataset from lecture demo, we had different measurements for each Location. 

We want you to consider this for the avocado prices dataset. For which categorical feature(s), if any, do we have separate measurements? Justify your answer by referencing the dataset.

<div class="alert alert-warning">

Solution_1.1
    
</div>

_Points:_ 4

We can see below that type and region are the 2 cateogircal features in this dataset. And we only got a sequence of sorted dates with a single row per date by fixing the region and the type. So each combination of region and type results in an unique time series in this datasset.

In [9]:
df.sort_values(by="Date")

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
51,2015-01-04,1.75,27365.89,9307.34,3844.81,615.28,13598.46,13061.10,537.36,0.00,organic,2015,Southeast
51,2015-01-04,1.49,17723.17,1189.35,15628.27,0.00,905.55,905.55,0.00,0.00,organic,2015,Chicago
51,2015-01-04,1.68,2896.72,161.68,206.96,0.00,2528.08,2528.08,0.00,0.00,organic,2015,HarrisburgScranton
51,2015-01-04,1.52,54956.80,3013.04,35456.88,1561.70,14925.18,11264.80,3660.38,0.00,conventional,2015,Pittsburgh
51,2015-01-04,1.64,1505.12,1.27,1129.50,0.00,374.35,186.67,187.68,0.00,organic,2015,Boise
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2018-03-25,1.36,908202.13,142681.06,463136.28,174975.75,127409.04,103579.41,22467.04,1362.59,conventional,2018,Chicago
0,2018-03-25,0.70,9010588.32,3999735.71,966589.50,30130.82,4014132.29,3398569.92,546409.74,69152.63,conventional,2018,SouthCentral
0,2018-03-25,1.42,163496.70,29253.30,5080.04,0.00,129163.36,109052.26,20111.10,0.00,organic,2018,SouthCentral
0,2018-03-25,1.70,190257.38,29644.09,70982.10,0.00,89631.19,89424.11,207.08,0.00,organic,2018,California
0,2018-03-25,1.34,1774776.77,63905.98,908653.71,843.45,801373.63,774634.09,23833.93,2905.61,conventional,2018,NewYork

In [10]:
df.sort_values(by=["type", "Date"])

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
51,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.00,conventional,2015,Albany
51,2015-01-04,1.00,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.00,conventional,2015,Atlanta
51,2015-01-04,1.08,788025.06,53987.31,552906.04,39995.03,141136.68,137146.07,3990.61,0.00,conventional,2015,BaltimoreWashington
51,2015-01-04,1.01,80034.32,44562.12,24964.23,2752.35,7755.62,6064.30,1691.32,0.00,conventional,2015,Boise
51,2015-01-04,1.02,491738.00,7193.87,396752.18,128.82,87663.13,87406.84,256.29,0.00,conventional,2015,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2018-03-25,1.04,14503.47,78.95,148.37,0.00,14276.15,9992.31,4283.84,0.00,organic,2018,Syracuse
0,2018-03-25,1.41,10028.49,138.15,773.22,0.00,9117.12,8208.82,908.30,0.00,organic,2018,Tampa
0,2018-03-25,1.55,1559967.20,121007.94,342853.10,1070.24,1093861.09,902774.79,190941.84,144.46,organic,2018,TotalUS
0,2018-03-25,1.60,271723.08,26996.28,77861.39,117.56,166747.85,87108.00,79495.39,144.46,organic,2018,West
0,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.00,organic,2018,WestTexNewMexico

In [11]:
df.sort_values(by=["region", "type", "Date"])

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
51,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
50,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany
49,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany
48,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany
47,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.0,organic,2018,WestTexNewMexico
3,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.0,organic,2018,WestTexNewMexico
2,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.0,organic,2018,WestTexNewMexico
1,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.0,organic,2018,WestTexNewMexico
0,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.0,organic,2018,WestTexNewMexico

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.2 Equally spaced measurements? 
rubric={points:4}

In the Rain in Australia dataset, the measurements were generally equally spaced but with some exceptions. How about with this dataset? Justify your answer by referencing the dataset.

<div class="alert alert-warning">

Solution_1.2
    
</div>

_Points:_ 4

From my observations the measurements are almost all equally spaced with 1 measurement every 7 days. However for the pair WestTexNewMexico and organic, we noticed that there's 2 exceptions: where 1 measurement had a 2 week gap and 1 measurement that had a 3 week gap.

In [12]:
# from lecture 20
def time_spacing_distribution(df, region="Albany", type="conventional"):
    """
    Plots the distribution of time spacing for a combination of given region and type
    
    Parameters:
        df (pd.DataFrame): The input DataFrame with columns 'Location' and 'Date'.
        region (str): The region (e.g., location) to analyze.
    """
    # Ensure 'Date' is in datetime format
    df['Date'] = pd.to_datetime(df['Date'])
    
    # Filter data for the given region
    region_type_data = df[(df['region'] == region) & (df['type'] == type)]
    
    if region_type_data.empty:
        print(f"No data available for region and type combination: {region}")
        return
    
    # Calculate time differences
    time_diffs = region_type_data['Date'].sort_values().diff().dropna()
    
    # Count the frequency of each time difference
    value_counts = time_diffs.value_counts().sort_index()
    
    # Display value counts
    print(f"Time spacing counts for {region} and {type}:\n{value_counts}\n")
    
    # # Plot the bar chart
    # plt.bar(value_counts.index.astype(str), value_counts.values, color='skyblue', edgecolor='black')
    # plt.title(f"Time Difference Distribution for {region}")
    # plt.xlabel("Time Difference (days)")
    # plt.ylabel("Frequency")
    # plt.xticks(rotation=45)
    # plt.grid(axis='y', linestyle='--', alpha=0.7)
    # plt.show()

In [13]:
for region in df["region"].unique():
    for type in df["type"].unique():
        time_spacing_distribution(df, region, type)

Time spacing counts for Albany and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Albany and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Atlanta and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Atlanta and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for BaltimoreWashington and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for BaltimoreWashington and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Boise and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Boise and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Boston and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Boston and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for BuffaloRochester and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for BuffaloRochester and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for California and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for California and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Charlotte and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Charlotte and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Chicago and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Chicago and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for CincinnatiDayton and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for CincinnatiDayton and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Columbus and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Columbus and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for DallasFtWorth and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for DallasFtWorth and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Denver and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Denver and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Detroit and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Detroit and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for GrandRapids and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for GrandRapids and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for GreatLakes and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for GreatLakes and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for HarrisburgScranton and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for HarrisburgScranton and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for HartfordSpringfield and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for HartfordSpringfield and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Houston and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Houston and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Indianapolis and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Indianapolis and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Jacksonville and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Jacksonville and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for LasVegas and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for LasVegas and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for LosAngeles and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for LosAngeles and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Louisville and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Louisville and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for MiamiFtLauderdale and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for MiamiFtLauderdale and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Midsouth and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Midsouth and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Nashville and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Nashville and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for NewOrleansMobile and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for NewOrleansMobile and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for NewYork and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for NewYork and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Northeast and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Northeast and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for NorthernNewEngland and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for NorthernNewEngland and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Orlando and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Orlando and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Philadelphia and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Philadelphia and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for PhoenixTucson and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for PhoenixTucson and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Pittsburgh and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Pittsburgh and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Plains and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Plains and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Portland and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Portland and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for RaleighGreensboro and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for RaleighGreensboro and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for RichmondNorfolk and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for RichmondNorfolk and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Roanoke and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Roanoke and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Sacramento and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Sacramento and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SanDiego and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SanDiego and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SanFrancisco and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SanFrancisco and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Seattle and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Seattle and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SouthCarolina and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SouthCarolina and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SouthCentral and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for SouthCentral and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Southeast and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Southeast and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Spokane and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Spokane and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for StLouis and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for StLouis and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Syracuse and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Syracuse and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Tampa and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for Tampa and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for TotalUS and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for TotalUS and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for West and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for West and organic:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for WestTexNewMexico and conventional:
Date
7 days    168
Name: count, dtype: int64

Time spacing counts for WestTexNewMexico and organic:
Date
7 days     163
14 days      1
21 days      1
Name: count, dtype: int64

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.3 Interpreting regions 
rubric={points:4}

In the Rain in Australia dataset, each location was a different place in Australia. For this dataset, look at the names of the regions. Do you think the regions are also all distinct, or are there overlapping regions? Justify your answer by referencing the data.

<div class="alert alert-warning">

Solution_1.3
    
</div>

_Points:_ 4

There seems to be some overlapping regions here. I see a hierarchy for US regions. There seems to be one region 'TotalUS' referencing the entire US, also state regions referencing a state such as 'California', but also distinct cities within US with regions such as 'Seattle'.

In [14]:
df["region"].unique()

<StringArray>
[             'Albany',             'Atlanta', 'BaltimoreWashington',
               'Boise',              'Boston',    'BuffaloRochester',
          'California',           'Charlotte',             'Chicago',
    'CincinnatiDayton',            'Columbus',       'DallasFtWorth',
              'Denver',             'Detroit',         'GrandRapids',
          'GreatLakes',  'HarrisburgScranton', 'HartfordSpringfield',
             'Houston',        'Indianapolis',        'Jacksonville',
            'LasVegas',          'LosAngeles',          'Louisville',
   'MiamiFtLauderdale',            'Midsouth',           'Nashville',
    'NewOrleansMobile',             'NewYork',           'Northeast',
  'NorthernNewEngland',             'Orlando',        'Philadelphia',
       'PhoenixTucson',          'Pittsburgh',              'Plains',
            'Portland',   'RaleighGreensboro',     'RichmondNorfolk',
             'Roanoke',          'Sacramento',            'SanDiego',
        'SanFrancisco',             'Seattle',       'SouthCarolina',
        'SouthCentral',           'Southeast',             'Spokane',
             'StLouis',            'Syracuse',               'Tampa',
             'TotalUS',                'West',    'WestTexNewMexico']
Length: 54, dtype: str

<!-- END QUESTION -->

<br><br>

We will use the entire dataset despite any location-based weirdness uncovered in the previous part.

We will be trying to forecast the avocado price. The function below is adapted from the lecture.

In [15]:
import pandas as pd


def create_lag_feature(
    df: pd.DataFrame,
    orig_feature: str,
    lag: int,
    groupby: list[str],
    new_feature_name: str | None = None,
    clip: bool = False,
) -> pd.DataFrame:
    """
    Create a lagged (or ahead) version of a feature, optionally per group.

    Assumes df is already sorted by time within each group and has unique indices.

    Parameters
    ----------
    df : pd.DataFrame
        The dataset.
    orig_feature : str
        Name of the column to lag.
    lag : int
        The lag:
          - negative → values from the past (t-1, t-2, ...)
          - positive → values from the future (t+1, t+2, ...)
    groupby : list of str
        Column(s) to group by if df contains multiple time series.
    new_feature_name : str, optional
        Name of the new column. If None, a name is generated automatically.
    clip : bool, default False
        If True, drop rows where the new feature is NaN.

    Returns
    -------
    pd.DataFrame
        A new dataframe with the additional column added.
    """
    if lag == 0:
        raise ValueError("lag cannot be 0 (no shift). Use the original feature instead.")

    # Default name if not provided
    if new_feature_name is None:
        if lag < 0:
            new_feature_name = f"{orig_feature}_lag{abs(lag)}"
        else:
            new_feature_name = f"{orig_feature}_ahead{lag}"

    df = df.copy()

    # Map your convention (negative=past, positive=future) to pandas shift
    # pandas: shift(+k) → past, shift(-k) → future
    periods = abs(lag) if lag < 0 else -lag

    df[new_feature_name] = (
        df.groupby(groupby, sort=False)[orig_feature]
          .shift(periods)
    )

    if clip:
        df = df.dropna(subset=[new_feature_name])

    return df

We first sort our dataframe properly:

In [16]:
df_sort = df.sort_values(by=["region", "type", "Date"]).reset_index(drop=True)
df_sort

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.0,organic,2018,WestTexNewMexico
18245,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.0,organic,2018,WestTexNewMexico
18246,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.0,organic,2018,WestTexNewMexico
18247,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.0,organic,2018,WestTexNewMexico
18248,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.0,organic,2018,WestTexNewMexico

We then call `create_lag_feature`. This creates a new column in the dataset `AveragePriceNextWeek`, which is the following week's `AveragePrice`. We have set `clip=True` which means it will remove rows where the target would be missing.

In [17]:
df_hastarget = create_lag_feature(df_sort, "AveragePrice", +1, ["region", "type"], "AveragePriceNextWeek", clip=True)
df_hastarget

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,AveragePriceNextWeek
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany,1.24
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany,1.17
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany,1.06
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany,0.99
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18243,2018-02-18,1.56,17597.12,1892.05,1928.36,0.00,13776.71,13553.53,223.18,0.0,organic,2018,WestTexNewMexico,1.57
18244,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.0,organic,2018,WestTexNewMexico,1.54
18245,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.0,organic,2018,WestTexNewMexico,1.56
18246,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.0,organic,2018,WestTexNewMexico,1.56
18247,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.0,organic,2018,WestTexNewMexico,1.62

Our goal is to predict `AveragePriceNextWeek`.

Let's split the data:

In [18]:
df_train = df_hastarget[df_hastarget["Date"] <= split_date]
df_test  = df_hastarget[df_hastarget["Date"] >  split_date]

<br><br>

<!-- BEGIN QUESTION -->

### 1.4 `AveragePrice` baseline 
rubric={points}

Soon we will want to build some models to forecast the average avocado price a week in advance. Before we start with any ML though, let's try a baseline. Previously we used `DummyClassifier` or `DummyRegressor` as a baseline. This time, we'll do something else as a baseline: we'll assume the price stays the same from this week to next week. So, we'll set our prediction of "AveragePriceNextWeek" exactly equal to "AveragePrice", assuming no change. That is kind of like saying, "If it's raining today then I'm guessing it will be raining tomorrow". This simplistic approach will not get a great score but it's a good starting point for reference. If our model does worse that this, it must not be very good. 

Using this baseline approach, what $R^2$ do you get on the train and test data?

<div class="alert alert-warning">

Solution_1.4
    
</div>

_Points:_ 4

We are getting $R^2$ score of 0.829 on the training set, and $R^2$ score of 0.763 on the test set.

In [19]:
y = df_train["AveragePriceNextWeek"]
y_hat = df_train["AveragePrice"]
train_r2 = r2_score(y, y_hat)
train_r2

0.8285800937261841

In [20]:
test_r2 = r2_score(df_test["AveragePriceNextWeek"], df_test["AveragePrice"])
test_r2

0.7631780188583048

In [21]:
assert not train_r2 is None, "Are you using the correct variable name?"
assert not test_r2 is None, "Are you using the correct variable name?"
assert sha1(str(round(train_r2, 3)).encode('utf8')).hexdigest() == 'b1136fe2a8918904393ab6f40bfb3f38eac5fc39', "Your training score is not correct. Are you using the right features?"
assert sha1(str(round(test_r2, 3)).encode('utf8')).hexdigest() == 'cc24d9a9b567b491a56b42f7adc582f2eefa5907', "Your test score is not correct. Are you using the right features?"

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.5 Forecasting average avocado price
rubric={points:10}

Now that the baseline is done, let's build some models to forecast the average avocado price a week later. Experiment with a few approachs for encoding the date. Justify the decisions you make. Which approach worked best? Report your test score and briefly discuss your results.

Benchmark: you should be able to achieve $R^2$ of at least 0.79 on the test set. I got to 0.80, but not beyond that. Let me know if you do better!

Note: because we only have 2 splits here, we need to be a bit wary of overfitting on the test set. Try not to test on it a ridiculous number of times. If you are interested in some proper ways of dealing with this, see for example sklearn's [TimeSeriesSplit](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html), which is like cross-validation for time series data.

<div class="alert alert-warning">

Solution_1.5
    
</div>

_Points:_ 10

Lets do some EDA first

In [22]:
df_train.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,AveragePriceNextWeek
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany,1.24
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany,1.17
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany,1.06
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany,0.99
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany,0.99

In [23]:
df_train.columns

Index(['Date', 'AveragePrice', 'Total Volume', '4046', '4225', '4770',
       'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type', 'year',
       'region', 'AveragePriceNextWeek'],
      dtype='str')

In [24]:
df_train.info()

<class 'pandas.DataFrame'>
Index: 15441 entries, 0 to 18222
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  15441 non-null  datetime64[us]
 1   AveragePrice          15441 non-null  float64
 2   Total Volume          15441 non-null  float64
 3   4046                  15441 non-null  float64
 4   4225                  15441 non-null  float64
 5   4770                  15441 non-null  float64
 6   Total Bags            15441 non-null  float64
 7   Small Bags            15441 non-null  float64
 8   Large Bags            15441 non-null  float64
 9   XLarge Bags           15441 non-null  float64
 10  type                  15441 non-null  str
 11  year                  15441 non-null  int64
 12  region                15441 non-null  str
 13  AveragePriceNextWeek  15441 non-null  float64
dtypes: datetime64[us](1), float64(10), int64(1), str(2)
memory usage: 1.8 MB

I'm noticing that there's 'Total Bags', 'Small Bags', 'Large Bags' and 'XLarge Bags' as our features, let's see whether there's a relationship between them.

In [25]:
diff = df_train["Total Bags"] - df_train["Small Bags"] - df_train["Large Bags"] - df_train["XLarge Bags"]
diff.max()

np.float64(1.0)

Seems like 'Total Bags' is pretty much the sum of the 3 bag categories. So we can drop this feature.

We do not have any missing data, nice! No imputation needed.

Lets break it down into numerical and categorical features.

Also we are dropping Date and year since both are just datetime information, which serves no purpose for us.

In [26]:
numeric_features = [
    "AveragePrice",
    "Total Volume",
    "4046",
    "4225",
    "4770",
    "Small Bags",
    "Large Bags",
    "XLarge Bags"
]
categorical_features = [
    "type",
    "region"
]
drop_features = [
    "Date",
    "year",
    "Total Bags"
]
target = ["AveragePriceNextWeek"]

In [27]:
# modified from lecture 20
def preprocess_features(
    train_df,
    test_df,
    numeric_features,
    categorical_features,
    drop_features,
    target
):

    all_features = set(numeric_features + categorical_features + drop_features + target)
    if set(train_df.columns) != all_features:
        print("Missing columns", set(train_df.columns) - all_features)
        print("Extra columns", all_features - set(train_df.columns))
        raise Exception("Columns do not match")

    numeric_transformer = make_pipeline(
        StandardScaler()
    )

    categorical_transformer = make_pipeline(
        OneHotEncoder(handle_unknown="ignore", sparse_output=False),
    )

    preprocessor = make_column_transformer(
        (numeric_transformer, numeric_features),
        (categorical_transformer, categorical_features),
        ("drop", drop_features),
    )
    preprocessor.fit(train_df)
    ohe_feature_names = (
        preprocessor.named_transformers_["pipeline-2"]
        .named_steps["onehotencoder"]
        .get_feature_names_out(categorical_features)
        .tolist()
    )
    new_columns = numeric_features + ohe_feature_names

    X_train_enc = pd.DataFrame(
        preprocessor.transform(train_df), index=train_df.index, columns=new_columns
    )
    X_test_enc = pd.DataFrame(
        preprocessor.transform(test_df), index=test_df.index, columns=new_columns
    )

    y_train = train_df[target]
    y_test = test_df[target]

    return X_train_enc, y_train, X_test_enc, y_test, preprocessor

In [28]:
X_train_enc, y_train, X_test_enc, y_test, preprocessor = preprocess_features(
    df_train,
    df_test,
    numeric_features,
    categorical_features,
    drop_features, 
    target
)

In [29]:
X_test_enc.head()

,AveragePrice,Total Volume,4046,4225,4770,Small Bags,Large Bags,XLarge Bags,type_conventional,type_organic,...,region_SouthCarolina,region_SouthCentral,region_Southeast,region_Spokane,region_StLouis,region_Syracuse,region_Tampa,region_TotalUS,region_West,region_WestTexNewMexico
143,0.715147,-0.225650,-0.228238,-0.198268,-0.214707,-0.235652,-0.206451,-0.172063,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144,0.934911,-0.230288,-0.228819,-0.207777,-0.215019,-0.239728,-0.209051,-0.172063,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145,0.617474,-0.224955,-0.229055,-0.193388,-0.214844,-0.237309,-0.212492,-0.172063,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,0.397709,-0.226089,-0.228757,-0.198330,-0.215082,-0.235607,-0.209892,-0.172063,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,0.666310,-0.226169,-0.229392,-0.198129,-0.214883,-0.235678,-0.208492,-0.172063,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Lets try out Logistic Regression

In [30]:
# Taken from lecture 20
def score_lr_print_coeff(preprocessor, train_df, y_train, test_df, y_test, X_train_enc):
    lr_pipe = make_pipeline(preprocessor, Ridge(max_iter=1000))
    lr_pipe.fit(train_df, y_train)
    print("Train score: {:.2f}".format(lr_pipe.score(train_df, y_train)))
    print("Test score: {:.2f}".format(lr_pipe.score(test_df, y_test)))
    lr_coef = pd.DataFrame(
        data=lr_pipe.named_steps["ridge"].coef_.flatten(),
        index=X_train_enc.columns,
        columns=["Coef"],
    )
    return lr_coef.sort_values(by="Coef", ascending=False)

In [31]:
score_lr_print_coeff(preprocessor, df_train, y_train, df_test, y_test, X_train_enc)

Train score: 0.84
Test score: 0.80

                                Coef
AveragePrice                0.332625
region_SanFrancisco         0.084067
region_HartfordSpringfield  0.080943
region_NewYork              0.063704
type_organic                0.047173
...                              ...
region_Denver              -0.044898
type_conventional          -0.047173
region_SouthCentral        -0.061247
region_DallasFtWorth       -0.061967
region_Houston             -0.071682

[64 rows x 1 columns]

<!-- END QUESTION -->

<br><br><br><br>

## Exercise 2: Short answer questions

<!-- BEGIN QUESTION -->

### 2.1 Time series

rubric={points:6}

The following questions pertain to Lecture 20 on time series data:

1. Sometimes a time series has missing time points or, worse, time points that are unequally spaced in general. Give an example of a real world situation where the time series data would have unequally spaced time points.
2. In class we discussed two approaches to using temporal information: encoding the date as one or more features, and creating lagged versions of features. Which of these (one/other/both/neither) two approaches would struggle with unequally spaced time points? Briefly justify your answer.
3. When studying time series modeling, we explored several ways to encode date information as a feature for the citibike dataset. When we used time of day as a numeric feature, the Ridge model was not able to capture the periodic pattern. Why? How did we tackle this problem? Briefly explain.

<div class="alert alert-warning">

Solution_2.1
    
</div>

_Points:_ 6

1. For example wildfire occurences. We cannot choose when wildfire happens, we can only record when it happens.
2. Encoding the date as one or more features is fine for unequally spaced points. But creating lag features may struggle since the previous measurement may not exist for our specified lag.
3. The problem of encoding the time of day as a numeric feature is that the model didn't capture the periodic pattern of dates, since it can only learn a linear function of the time of day. We tackled this problem by extracting patterns from the dates such as the month, day in the week etc and use them as categorical features with one hot encoding.

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 2.2 Computer vision 
rubric={points:6}

The following questions pertain to the lecture on multiclass classification and introduction to computer vision. 

1. How many parameters (coefficients and intercepts) will `sklearn`’s `LogisticRegression()` model learn for a four-class classification problem, assuming that you have 10 features? Briefly explain your answer.
2. In Lecture 19, we briefly discussed how neural networks are sort of like `sklearn`'s pipelines, in the sense that they involve multiple sequential transformations of the data, finally resulting in the prediction. Why was this property useful when it came to transfer learning?
3. Imagine that you have a small dataset with ~1000 images containing pictures and names of 50 different Computer Science faculty members from UBC. Your goal is to develop a reasonably accurate multi-class classification model for this task. Describe which model/technique you would use and briefly justify your choice in one to three sentences.

<div class="alert alert-warning">

Solution_2.2
    
</div>

_Points:_ 6

1. We would learn $(10 + 1) \times 4 = 44$ parameters. We have 10 parameters for features, and 1 parameter for the intercept term for each class label. Multiply that by the number of class labels we have and we get 44.
2. Because transfer learning is the act of us using pretrained powerful models as a baseline for futher training, we can do the same here by taking most of the previous layers of transformations and modifying the last few layers customized for what we want to do.
3. I would use a pre-trained model trained on large datasets to obtain latent features from our small dataset. Then use logistic regression on these features to classify faculty members.

<!-- END QUESTION -->

<br><br>

Before submitting your assignment, please make sure you have followed all the instructions in the Submission Instructions section at the top. 

Here is a quick checklist before submitting: 

- [ ] Restart kernel, clear outputs, and run all cells from top to bottom.  
- [ ] `.ipynb` file runs without errors and contains all outputs.  
- [ ] Only `.ipynb` and required output files are uploaded (no extra files).  
- [ ] Execution numbers start at **1** and are in order.  
- [ ] If `.ipynb` is too large and doesn't render on Gradescope, also upload a PDF/HTML version.  
- [ ] Reviewed the [CPSC 330 homework instructions](https://ubc-cs.github.io/cpsc330-2025W2/docs/homework-instructions).

![](img/eva-well-done.png)